# Generated by Django 2.0.7 on 2018-07-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180731_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_note',
            name='note_ptr',
        ),
        migrations.RemoveField(
            model_name='personal_note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Personal_Note',
        ),
    ]
